name: Subscribe
description: Join the Velvet Afterthoughts mailing list.
title: "subscribe request"
body:
  - type: input
    id: email
    attributes:
      label: Your email address
      description: Enter your email to subscribe.
      placeholder: you@example.com
    validations:
      required: true
